# Generated by Django 5.2.4 on 2025-07-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
