# Generated by Django 5.2.4 on 2025-08-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_event_id_event__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='createdBy',
            field=models.CharField(max_length=255),
        ),
    ]
